### PR TITLE
Fixes for reliability and compilation cancellation

### LINKED ISSUE #9: document link lost when switching documents
That functionality of jumping to the corresponding assembly and vice-versa is lost as soon as you switch to another .cpp file.
Going back to the original one does not bring it back.

### PR DESCRIPTION
**Pull request by appden**
This addresses a few issues:

- Updates to the compilation db or custom command would not result in recompile
- Updating the source file wouldn't reliably result in a re-compile nor kill pending compilation
- Manually cancelling would not kill the processes, which could get stuck
- Reloading the extension would not dispose all subscription or kill processes
- Decorations would go away when switching tabs (fixes #9)

P.S. Sorry for the large changeset, but it should be easier to review ignoring whitespace. 😀

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -28,9 +28,19 @@ export function activate(context: ExtensionContext): void {
...
             setTimeout(() => decorator.updateSelection(srcEditor), 500);
 
-            workspace.onDidCloseTextDocument((d: TextDocument) => {
-                if (d.uri == srcEditor.document.uri) provider.unload(d.uri);
+            // keep reference to documents since editors can change under us
+            const srcDocument = srcEditor.document;
+            const asmDocument = asmEditor.document;
+
+            const disposable = workspace.onDidCloseTextDocument((d: TextDocument) => {
+                if (d === srcDocument || d === asmDocument) {
```
Comment (harikrishnan94) [inline src/extension.ts:36]: I'm able to test the case of `disposable` being invoked after closing `asmDocument`. This is not related to your patch, but in general even without your patch. Were you able repro the case of disposable being invoked after closing the asmDocument?

**Comment by harikrishnan94** [comment]
Can you pls, enable [commit signature verification](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification) in your machine for your account?
I've enabled **Require signed commit** as branch protection rule to check before merge.

File: src/extension.ts (hunk 1 above)
Comment (appden) [reply src/extension.ts:36]: Yea, great question, I noticed that too. Although, sometime later after closing the asm tab, `onDidCloseTextDocument` would get called for the `asmDocument` (typically after `c_cpp_properties.json` would get released as well, so VS Code seems to keep it cached for some time). I figured I'd leave that in for completeness/correctness anyways since it does eventually get called, at least sometimes. ¯\_(ツ)_/¯

**Comment by appden** [comment]
Thanks! I just force pushed new signed commits. 😀

File: src/extension.ts (hunk 1 above)
Comment (harikrishnan94) [reply src/extension.ts:36]: Right. I encountered the same behaviour too. `leave that in for completeness/correctness ` -> +1

**Comment by harikrishnan94** [comment]
Merged with minor re-wording of commit message. Thanks for your contribution.
Published to vscode marketplace as v0.7.0.
